name: build

on:
  pull_request:
    branches: 'master'
    paths:
      - '.github/workflows/build.yml'
      - 'Dockerfile'
  push:
    branches: 'master'
    paths:
      - '.github/workflows/build.yml'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prepare
        run: |
          echo ::set-output name=version::latest
          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=docker_username::crazymax
          echo ::set-output name=docker_image::crazymax/loop
      -
        name: Docker Build
        run: |
          docker build \
            --build-arg "BUILD_DATE=${{ steps.prepare.outputs.build_date }}" \
            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
            --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
            --file Dockerfile .
      -
        name: Docker Login
        if: success() && github.event_name != 'pull_request'
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${{ steps.prepare.outputs.docker_username }}" --password-stdin
      -
        name: Docker Push
        if: success() && github.event_name != 'pull_request'
        run: |
          docker push ${{ steps.prepare.outputs.docker_image }}
      -
        name: Docker Check Manifest
        if: always() && github.event_name != 'pull_request'
        run: |
          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
